// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHG3YA-ty2rP4T5pr0nXncRXatoxqplyk',
    appId: '1:235099134968:android:fed6d67c46c82f7605140d',
    messagingSenderId: '235099134968',
    projectId: 'muslim-9d4ea',
    authDomain: 'muslim-9d4ea.firebaseapp.com',
    storageBucket: 'gs://muslim-9d4ea.appspot.com',
    measurementId: 'G-ECMDFE63S7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHG3YA-ty2rP4T5pr0nXncRXatoxqplyk',
    appId: '1:235099134968:android:fed6d67c46c82f7605140d',
    messagingSenderId: '235099134968',
    projectId: 'muslim-9d4ea',
    authDomain: 'muslim-9d4ea.firebaseapp.com',
    storageBucket: 'gs://muslim-9d4ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHG3YA-ty2rP4T5pr0nXncRXatoxqplyk',
    appId: '1:235099134968:android:fed6d67c46c82f7605140d',
    messagingSenderId: '235099134968',
    projectId: 'muslim-9d4ea',
    authDomain: 'muslim-9d4ea.firebaseapp.com',
    storageBucket: 'gs://muslim-9d4ea.appspot.com',
    iosClientId: '1045475764615-sh6bdtfvq5gi9hdi9elu247v7usqsvpl.apps.googleusercontent.com',
    iosBundleId: 'com.mrezys',
  );
}
